# Generated by Django 5.1.7 on 2025-03-18 22:30

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('skills_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('internship', 'Internship')], max_length=50)),
                ('url', models.URLField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
                'indexes': [models.Index(fields=['job_title'], name='joblistings_job_tit_a6f570_idx'), models.Index(fields=['company_name'], name='joblistings_company_a0861e_idx'), models.Index(fields=['location'], name='joblistings_locatio_54eeb8_idx'), models.Index(fields=['posted_at'], name='joblistings_posted__e3a7f4_idx')],
            },
        ),
    ]
