# Generated by Django 5.1.7 on 2025-03-18 22:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joblistings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.DecimalField(decimal_places=2, help_text='AI-generated score based on match percentage (0-100)', max_digits=5)),
                ('recommended_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='joblistings.joblisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Recommendation',
                'verbose_name_plural': 'Job Recommendations',
                'ordering': ['-relevance_score', '-recommended_at'],
                'indexes': [models.Index(fields=['-relevance_score'], name='jobrecommen_relevan_e69617_idx'), models.Index(fields=['-recommended_at'], name='jobrecommen_recomme_2bd670_idx')],
            },
        ),
    ]
